export const site = {
  name: "Beyond Borders",
  legalName: "Beyond Borders Real Estate Ltd",
  tagline: "Achieving more...",
  description:
    "Smart and luxury homes, estates, and land investments across Abuja and Port Harcourt — buy & build packages, finished smart homes, and titled land.",
  url: "https://www.beyondborders.ng",
  email: "info@beyondborders.ng",
  emailAlt: "Beyondborders234@gmail.com",
  phone: "+234 907 171 1222",
  phoneAlt: "+234 905 595 9509",
  phoneExtra: "+234 904 319 7743",
  phonePh: "+234 902 849 7393",
  phonePhAlt: "+234 814 934 4813",
  whatsapp: "2349071711222",
  address: {
    line1: "Suite A13D Platinum Plaza",
    line2: "opposite Mabushi Ultramodern Market, Jahi, Abuja, NG",
  },
  addressAlt: {
    line1: "Plot 84, Victor B.K Crescent",
    line2:
      "Off Garba Idris Street, after Lake View Homes, Behind Customs Quarters, Jahi, Abuja",
  },
  addressPh: {
    line1: "First Floor, Vine Yard Plaza",
    line2: "88 Woji Road, GRA Phase 2, Port Harcourt, Rivers State",
  },
  social: {
    facebook: "https://www.facebook.com/profile.php?id=100074835450660",
    instagram: "https://www.instagram.com/beyondbordersng",
    instagramPh: "https://www.instagram.com/beyondbordersph_",
  },
  logo: "/media/Main_logo.png",
  logoHighRes: "/media/Main-Logo.png",
  logoMark: "/media/logo-mark.png",
  logoLight: "/media/logo-light.png",
  favicon: "/icon.png",
  ogImage: "/og-image.png",
  downloads: {
    companyProfile: "/media/brochures/beyond-borders-company-brochure.pdf",
    portfolioFlyer: "/media/brochures/beyond-borders-portfolio-flyer.pdf",
  },
  videos: {
    whiteCity: "/media/video/white-city-estates.mp4",
    products: "/media/video/portfolio-products.mp4",
    logoIntro: "/media/video/brand-logo-intro.mp4",
    abujaOngoing: "/media/video/abuja-ongoing.mp4",
    whiteCityCgi: "/media/video/white-city-cgi-tour.mp4",
    whiteCity3d: "/media/video/white-city-abuja-3d.mp4",
    whiteCityInterior: "/media/video/white-city-interior-tour.mp4",
    aspen2Promo: "/media/video/white-city-aspen-2-promo.mp4",
  },
  promo: {
    eyebrow: "50% Promo Still On",
    title: "Time Never Waits. Neither Do The Best Properties.",
    body: "Get access to exclusive luxury listings — premium properties, trust & transparency, expert guidance, and end-to-end support. 50% Independence Day promo remains active across White City, Royal City, Aspen, KingsCity, White Court, and Port Harcourt land offerings.",
    ctaLabel: "Schedule an Inspection",
    ctaHref: "/schedule-an-inspection/",
    image: "/media/campaigns/time-never-waits-promo.jpg",
  },
  stats: {
    sqFt: "8 million+ sq ft",
    estates: "18+ offerings",
    lands: "Abuja & Port Harcourt · hectares available",
  },
  services: [
    "Architectural Design",
    "General Construction",
    "Building Construction",
    "Interior Design",
    "Flooring & Roofing",
    "INT/EXT Painting",
    "Property Sales",
    "Site & Serviced Plots",
    "Project Management",
    "Estate & Facility Management",
    "Turnkey Projects",
    "Smart Homes",
    "Land Banking / Hectares",
    "Buy & Build Advisory",
  ] as const,
  nav: [
    { label: "Home", href: "/" },
    {
      label: "About",
      href: "/our-company/",
      children: [{ label: "Our Company", href: "/our-company/" }],
    },
    {
      label: "Projects",
      href: "/houses/",
      children: [
        { label: "The Borderless", href: "/houses-beyond-towers/" },
        { label: "White City Beverly", href: "/houses-white-city-beverly/" },
        { label: "The White Court", href: "/houses-white-court/" },
        { label: "Halaand Estate", href: "/houses-halaand-estate/" },
        { label: "White City Savanah", href: "/houses-white-city-savanah/" },
        { label: "White City Dallas", href: "/houses-white-city-dallas/" },
        { label: "Royal City Beverly", href: "/houses-royal-city-beverly/" },
        { label: "Royal City Phase 1", href: "/houses-royal-city-phase-1/" },
        { label: "White City Aspen 2", href: "/houses-white-city-aspen-2/" },
        { label: "KingsCity Davos", href: "/houses-kingscity-davos/" },
        { label: "Lifecamp", href: "/houses-beyond-borders-lifecamp/" },
        { label: "Guzape", href: "/houses-beyond-borders-guzape/" },
        { label: "Jahi", href: "/houses-beyond-borders-jahi/" },
        { label: "Hectare O'Clock", href: "/lands-hectare-abuja/" },
        { label: "Kings City Manhattan (PH)", href: "/lands-kingscity-manhattan/" },
        { label: "Convention Grounds (PH)", href: "/houses-christ-embassy-convention/" },
      ],
    },
    { label: "Schedule an Inspection", href: "/schedule-an-inspection/" },
    { label: "Contact Us", href: "/contact-us/" },
  ],
  footerProjects: [
    { label: "Estates", href: "/estates/" },
    { label: "Houses", href: "/houses/" },
    { label: "Lands", href: "/lands/" },
    { label: "Schedule an Inspection", href: "/schedule-an-inspection/" },
  ],
} as const;

export type SiteConfig = typeof site;
